name: geolocator_flutterflow_plugin
description: "A new Flutter plugin project."
repository: https://github.com/vishantjawallia/geolocator_flutterflow_plugin/
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=2.8.0"


flutter:
  plugin:
    platforms:
      android:
        default_package: geolocator_android
      ios:
        default_package: geolocator_apple
      macos:
        default_package: geolocator_apple
      web:
        default_package: geolocator_web
      windows:
        default_package: geolocator_windows

dependencies:
  flutter:
    sdk: flutter

  geolocator_platform_interface: ^4.2.3
  geolocator_android: ^4.6.0
  geolocator_apple: ^2.3.8
  geolocator_web: ^4.1.1
  geolocator_windows: ^0.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.1 <5.0.0"
  mockito: ^5.0.0-nullsafety.7
  plugin_platform_interface: ^2.1.8  
